image: openjdk:15-alpine

pipelines:
    branches:
        master:
            -   step:
                    name: Build docs
                    script:
                        - apk add --no-cache wget graphviz ttf-dejavu git make bash openssh-client
                        - git remote add github git@github.com:HEPTACOM/heptaconnect-docs.git
                        - git push --force github master
                        - wget "https://sourceforge.net/projects/plantuml/files/1.2020.12/plantuml.1.2020.12.jar/download" -O /tmp/plantuml.jar
                        - PLANTUML="java -Djava.awt.headless=true -jar /tmp/plantuml.jar" make build
                        - git checkout -b gh-pages
                        - git add --all
                        - test $(git diff --name-only --cached | wc -l) -eq 0 || git commit -m "Build gh-pages"
                        - git push --force origin gh-pages
                        - git push --force github gh-pages
