image: node:14-alpine

definitions:
    steps:
        -   step: &default
                artifacts:
                    - 'docs/**'
        -   step: &build-uml
                <<: *default
                name: Build UML
                image: openjdk:15-alpine
                script:
                    - apk add --no-cache wget graphviz ttf-dejavu make bash
                    - wget "https://sourceforge.net/projects/plantuml/files/1.2020.12/plantuml.1.2020.12.jar/download" -O /tmp/plantuml.jar
                    - PLANTUML="java -Djava.awt.headless=true -jar /tmp/plantuml.jar" make uml
        -   step: &build-docs
                <<: *default
                image: squidfunk/mkdocs-material
                name: Build documentation assets
                script:
                    - make build
        -   step: &commit-built-docs
                <<: *default
                name: Commit docs
                script:
                    - apk add --no-cache git openssh-client
                    - mv .gh-pages-gitignore .gitignore
                    - git stash
                    - git checkout -b gh-pages
                    - git stash apply
                    - git add --all
                    - test $(git diff --name-only --cached | wc -l) -eq 0 || git commit -m "Build gh-pages"
                    - git push --force origin gh-pages
        -   step: &publish-docs
                <<: *default
                name: Publish to github
                script:
                    - apk add --no-cache git openssh-client
                    - git remote add github git@github.com:HEPTACOM/heptaconnect-docs.git
                    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
                    - git remote update
                    - git fetch --all
                    - git push --force github gh-pages
                    - git checkout --track origin/master
                    - git push --force github master

pipelines:
    branches:
        master:
            -   step: *build-uml
            -   step: *build-docs
            -   step: *commit-built-docs
        gh-pages:
            -   step:
                    name: Skip for manual step
                    script:
                        - echo "hello"
            -   step:
                    <<: *publish-docs
                    deployment: production
                    trigger: manual
    pull-requests:
        '**':
            -   step: *build-uml
            -   step: *build-docs
