site_name: HEPTAconnect
use_directory_urls: true

repo_url: https://github.com/HEPTACOM/heptaconnect-docs
repo_name: HEPTAconnect Docs

# Copyright
copyright: HEPTACOM solution for medium and large enterprises

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - meta
    - pymdownx.highlight
    - pymdownx.snippets:
        base_path: snippets
        check_paths: true
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: false

# Plugins
plugins:
    - search
    - git-revision-date-localized:
        fallback_to_build_date: true
    - gen-files:
        scripts:
            - generators/inject_role_metadata.py
    - with-pdf:
        author: HEPTACOM GmbH
        cover: true
        cover_title: HEPTAconnect
        cover_subtitle: ''
        render_js: false
    - meta-descriptions:
        export_csv: true
    - section-index
    - build_plantuml:
          render: local
          bin_path: plantuml
          output_format: svg
          diagram_root: uml
          output_folder: ../docs/assets/uml
          input_folder: src
          input_extensions: puml

# Theme
theme:
    name: material
    custom_dir: overrides
    features:
        - navigation.tabs
    language: en
    logo: assets/gfx/heptaconnect-icon.svg
    favicon: assets/favicon/favicon-32x32.png
    icon:
        repo: fontawesome/brands/github
    palette:
        -
            media: "(prefers-color-scheme: light)"
            scheme: default
            toggle:
                icon: fontawesome/solid/toggle-off
                name: Switch to dark mode
        -
            media: "(prefers-color-scheme: dark)"
            scheme: slate
            toggle:
                icon: fontawesome/solid/toggle-on
                name: Switch to light mode
    font: false
    search_index_only: true

extra_css:
    - assets/stylesheets/extra.css
    - assets/stylesheets/vendor/highlight.js/atom-one-dark.min.css

extra_javascript:
    - assets/javascripts/vendor/highlight.js/highlight.min.js
    - assets/javascripts/config.js

# Customization
extra:
    social:
        -
            icon: fontawesome/brands/github
            link: https://github.com/topics/heptaconnect
        -
            icon: fontawesome/brands/twitter
            link: https://twitter.com/heptacom_gmbh

# Page tree
nav:
    - index.md
    - Portal Developer:
        - guides/portal-developer/index.md
        - Portal: guides/portal-developer/portal.md
        - Explorer: guides/portal-developer/explorer.md
        - Emitter: guides/portal-developer/emitter.md
        - Receiver: guides/portal-developer/receiver.md
        - Morphers: guides/portal-developer/morphers.md
        - Key value storage: guides/portal-developer/key-value-storage.md
        - Cronjobs: guides/portal-developer/cronjobs.md
        - Webhooks: guides/portal-developer/webhooks.md
        - Status reporting: guides/portal-developer/status-reporting.md
        - Explorer decoration: guides/portal-developer/explorer-decoration.md
        - Emitter decoration: guides/portal-developer/emitter-decoration.md
        - Receiver decoration: guides/portal-developer/receiver-decoration.md
        - Direct emission explorer: guides/portal-developer/direct-emission-explorer.md
        - Dependency injection: guides/portal-developer/dependency-injection.md
        - Default utilities: guides/portal-developer/default-utilities.md
        - Short notation for flow components: guides/portal-developer/short-notation-for-flow-components.md
    - Playground:
        - guides/playground/index.md
        - First time:
            - guides/playground/first-time.md
            - with Shopware 6: guides/playground/first-time/with-shopware-6.md
        - Commandline: guides/playground/command-line.md
        - Add portals: guides/playground/add-portals.md
        - Contribution: guides/playground/contribution.md
    - Contributor:
        - guides/contributor/index.md
        - Contributor License Agreement: guides/contributor/cla.md
    - Reference:
        - Overview: reference/index.md
        - General resources:
            - Package structure: reference/general-resources/package-structure.md
            - Data flow: reference/general-resources/data-flow.md
            - Mapping: reference/general-resources/mapping.md
        - ADRs:
            - Telemetry recording: reference/adr/2020-01-27-telemetry-recording.md
            - Contracts and interfaces: reference/adr/2020-04-30-contracts-and-interfaces.md
            - Architecture decision records: reference/adr/2020-08-10-architecture-decision-records.md
            - Parallelization locks: reference/adr/2020-08-28-parallelization-locks.md
            - Portal status reporters: reference/adr/2020-10-15-portal-status-reporters.md
            - Job messages and payload: reference/adr/2020-10-30-job-messages-and-payload.md
            - Portal service container: reference/adr/2020-12-10-portal-service-container.md
            - Direct emission exploration: reference/adr/2021-02-03-direct-emission-exploration.md
            - Portal dependency injection implementation: reference/adr/2021-04-13-portal-dependency-injection-implementation.md
            - Flow component short notation: reference/adr/2021-06-17-flow-component-short-notation.md
        - Glossary: reference/glossary.md
        - License: reference/license.md
