site_name: HEPTAconnect

repo_url: https://github.com/HEPTACOM/heptaconnect-docs
repo_name: HEPTAconnect Docs

# Copyright
copyright: HEPTAconnect - a HEPTACOM solution for medium and large enterprises

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - pymdownx.highlight
    - pymdownx.snippets:
        base_path: snippets
        check_paths: true
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: false

# Plugins
plugins:
    - search

# Theme
theme:
    name: material
    custom_dir: overrides
    features:
        - navigation.tabs
    language: en
    logo: assets/gfx/heptaconnect-icon.svg
    icon:
        repo: fontawesome/brands/github
    palette:
        -
            media: "(prefers-color-scheme: light)"
            scheme: default
            toggle:
                icon: fontawesome/solid/toggle-off
                name: Switch to dark mode
        -
            media: "(prefers-color-scheme: dark)"
            scheme: slate
            toggle:
                icon: fontawesome/solid/toggle-on
                name: Switch to light mode

    search_index_only: true

extra_css:
    - assets/stylesheets/extra.css
    - assets/stylesheets/vendor/highlight.js/atom-one-dark.min.css

extra_javascript:
    - assets/javascripts/vendor/highlight.js/highlight.min.js
    - assets/javascripts/config.js

# Customization
extra:
    social:
        -
            icon: fontawesome/brands/github
            link: https://github.com/topics/heptaconnect
        -
            icon: fontawesome/brands/twitter
            link: https://twitter.com/heptacom_gmbh

# Page tree
nav:
    - Home: index.md
    - Portal Developer:
        - Home: guides/portal-developer/index.md
        - Portal: guides/portal-developer/portal.md
        - Explorer: guides/portal-developer/explorer.md
        - Emitter: guides/portal-developer/emitter.md
        - Receiver: guides/portal-developer/receiver.md
        - Morphers: guides/portal-developer/morphers.md
        - Key value storage: guides/portal-developer/key-value-storage.md
        - Cronjobs: guides/portal-developer/cronjobs.md
        - Webhooks: guides/portal-developer/webhooks.md
        - Status reporting: guides/portal-developer/status-reporting.md
        - Explorer decoration: guides/portal-developer/explorer-decoration.md
        - Emitter decoration: guides/portal-developer/emitter-decoration.md
        - Receiver decoration: guides/portal-developer/receiver-decoration.md
        - Direct emission explorer: guides/portal-developer/direct-emission-explorer.md
        - Dependency injection: guides/portal-developer/dependency-injection.md
        - Default utilities: guides/portal-developer/default-utilities.md
        - Short notation for flow components: guides/portal-developer/short-notation-for-flow-components.md
    - Reference:
        - Overview: reference/index.md
        - License: reference/license.md
