@startuml

!include ../../include/skin.puml

package Framework {
    rectangle "Core" as C $colorHighlight
    rectangle "Dataset-Base" as DB
    rectangle "Portal-Base" as PB
}

rectangle "Dataset-Ecommerce" as DE
rectangle "Portal-BusinessCentral" as PBC
rectangle "Portal-ShopwarePlatform" as PSP

C --|> PB
C --|> DB
DE --|> DB
PB -right-|> DB
PBC -up-|> PB
PBC --|> DE
PSP -up-|> PB
PSP --|> DE

@enduml
